apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: determine-image-tag
spec:
  # TODO(ROX-27384): this is a task for the Scanner and Collector repos, unify with the StackRox one.
  description: Determines the tag for the output image using the StackRox convention from 'make tag' output.
  params:
  - name: TAG_SUFFIX
    description: Suffix to append to generated image tag.
    type: string
  - name: SOURCE_ARTIFACT
    description: The Trusted Artifact URI pointing to the artifact with
      the application source code. This should be the result of the git-clone task,
      results from other tasks might fail as dirty.
    type: string
  results:
  - name: IMAGE_TAG
    description: Image Tag determined by custom logic.
  volumes:
  - name: workdir
    emptyDir: { }
  stepTemplate:
    volumeMounts:
    - mountPath: /var/workdir
      name: workdir
  steps:
  - name: use-trusted-artifact
    image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:ff35e09ff5c89e54538b50abae241a765b2b7868f05d62c4835bebf0978f3659
    args:
    - use
    - $(params.SOURCE_ARTIFACT)=/var/workdir/source
  - name: determine-image-tag
    image: registry.access.redhat.com/ubi9:latest@sha256:1057dab827c782abcfb9bda0c3900c0966b5066e671d54976a7bcb3a2d1a5e53
    workingDir: /var/workdir/source
    script: |
      #!/usr/bin/env bash
      set -euo pipefail
      dnf -y upgrade --nobest
      dnf -y install git make

      .konflux/scripts/fail-build-if-git-is-dirty.sh

      # First, try take git tag if it's a tagged commit.
      tag="$(git tag --points-at)"
      if [[ -z "$tag" ]]; then
        # If not, use make target's output.
        tag="$(make --quiet --no-print-directory tag)"
      elif [[ "$(wc -l <<< "$tag")" -gt 1 ]]; then
        >&2 echo -e "Error: the HEAD commit has multiple tags, don't know which one to choose:\n$tag"
        exit 5
      fi

      echo -n "${tag}$(params.TAG_SUFFIX)" | tee "$(results.IMAGE_TAG.path)"
