apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: install-infractl
spec:
  description: Download infractl.
  results:
  - name: infractl-bin
    description: Path to the infractl binary.
  steps:
  - name: download-infractl
    image: quay.io/konflux-qe-incubator/konflux-qe-tools:latest@sha256:88d70f9c61d2059e3a084fe6f2fb3ac341bc65efe9c6ba994e42a61bbb54fcba
    workingDir: /workspace/bin
    script: |
      #!/usr/bin/env bash

      set -o errexit
      set -o nounset
      set -o pipefail
      
      curl --fail -sL https://infra.rox.systems/v1/cli/linux/amd64/upgrade \
        | jq -r ".result.fileChunk" \
        | base64 -d \
      > infractl
      chmod +x infractl
      printf "INFO: $(./infractl --version)\n" 
      echo "/workspace/bin/infractl" > $(results.infractl-bin.path)
